language: java
jdk:
  - oraclejdk8
before_install:
  - sudo add-apt-repository -y ppa:cwchien/gradle 
  - sudo apt-get update 
  - sudo apt-get install -y gradle-ppa
  - export PATH=/usr/bin:$PATH
  - echo $PATH
  - which gradle
  - gradle --version
